---
- name: Prepare
  hosts: all
  become: true

  tasks:
    - name: Include role mamono210.swapfile
      ansible.builtin.include_role:
        name: 'mamono210.swapfile'
      vars:
        swapfile_size: '10G'

    - name: Include role {{ item }}
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - mamono210.aws_bootstrap
        - mamono210.aws_s3_get
      loop_control:
        label: "{{ item }}"
